name: Publish to Docker Registry

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Generate timestamp
      run: echo "TIMESTAMP=$(date +%s)" >> $GITHUB_ENV

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag vfilby/docker-openssh_rsync:${TIMESTAMP}

    - name: Push the Docker image with timestamp tag
      run: docker push vfilby/docker-openssh_rsync:${TIMESTAMP}

    - name: Push the Docker image with latest tag
      run: docker push vfilby/docker-openssh_rsync
